version: '3.8'

name: opd-professional-score
services:
  postgres:
    container_name: opd-professional-score-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - opd-professional-score:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
volumes:
  opd-professional-score:
networks:
  internal:
    name: internal
  external:
    name: external