name: Assign Reviewer for PR

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.ASSIGNER_TOKEN }}
          REVIEWER: 'TheGeniusOfEternity'
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: |
          curl -X POST \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PULL_REQUEST_NUMBER}/requested_reviewers \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"reviewers": ["${REVIEWER}"]}'
